name: WiseCash Help
baseurl: /help
permalink: /:title
gems: ['jekyll-assets']
exclude: [vendor]
assets:
  js_compressor:  uglifier
  css_compressor: sass
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
