name: WiseCash Help
permalink: /:title
bloghost: "https://help.wisecashhq.com"
gems: ['jekyll-assets']
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"